#Sample Kubernetes Pod to deploy the app contained in mohanrangayama/getting-started-k8s
apiVersion: v1
kind: Pod
metadata:
   name: hello-pod
   labels:
     app: web
spec:
  containers:
    - name: web-ctr
      image: mohanrangayama:getting-started-k8s:1.0
      ports:
        - containerPort: 8080
